apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: iris-code-pipeline # executable id, must be unique across all your workflows (YAML files), please modify this to any value (e.g. code-pipeline-12345) if you are not the only user of your SAP AI Core instance.
  annotations:
    scenarios.ai.sap.com/description: "add custom code to SAP AI Core"
    scenarios.ai.sap.com/name: "Code (Tutorial)"
    executables.ai.sap.com/description: "Trains model on iris flowers species"
    executables.ai.sap.com/name: "iris flower (Sklearn Example)"
  labels:
    scenarios.ai.sap.com/id: "learning-code"
    ai.sap.com/version: "4.0"
spec:
  imagePullSecrets:
    - name: irisdatareposapveg # your docker registry secret
  entrypoint: mypipeline
  templates:
  - name: mypipeline
    steps:
    - - name: myclassifier
        template: mycodeblock1

  - name: mycodeblock1
    container:
      image: docker.io/umashankar8331/aicore_application:1.1.0 # Your docker image name
      command: ["/bin/sh", "-c"]
      args:
        - "python main.py"
